REBOL []
foreach code [
[length? system/catalog/natives]
[mold system/catalog/natives]
[length? system/catalog/actions]
[mold system/catalog/actions]
[none? find system/catalog/natives 'integer?]
[none? find system/catalog/actions 'integer?]
[none? find system/catalog/natives 'any-type?]
[none? find system/catalog/natives 'show]
[none? find system/catalog/natives 'xtest]
[type? :integer?]
[type? :add]
[type? :print]
[type? :pickz]
[type? :random]
] [set/any 'e try code print either unset? get/any 'e [{#unset}] [mold/flat/all either error? e [reduce [e/id e/arg1 e/arg2 e/arg3]] [e]]]
