REBOL []
foreach code [
[date? now]
[date? now/precise]
[none? now/date/time]
[time? now/time]
[time? now/zone]
[zero? now/utc/zone]
[integer? now/weekday]
[integer? now/yearday]
[integer? now/year]
[integer? now/month]
[integer? now/day]
[date? now/date/precise]
[e: try [now/year/month] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [now/precise/time/date] reduce [e/id e/arg1 e/arg2 e/arg3]]
[also 1 2]
[also () 2]
[also 1 ()]
[x: 0 also 1 x: 2 x]
[comment "x"]
[comment [a b]]
[e: try [comment] reduce [e/id e/arg1 e/arg2 e/arg3]]
[to-value ()]
[to-value none]
[to-value 1]
[to-value [a]]
[trace off]
[trace 0]
[trace/back off]
[trace/function off]
[e: try [trace "x"] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [trace 1.5] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [trace none] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [load-extension 1] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [load-extension/dispatch #{00} none] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [do-callback 1] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [do-commands 1] reduce [e/id e/arg1 e/arg2 e/arg3]]
[integer? access-os 'pid]
[integer? access-os 'PID]
[integer? access-os 'uid]
[integer? access-os 'euid]
[integer? access-os 'gid]
[integer? access-os 'egid]
[e: try [access-os 'nope] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os 1] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os/set 'pid "x"] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os/set 'pid [1]] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os/set 'pid [1 2 3]] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os/set 'pid [a b]] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os/set 'pid [1 x]] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os/set 'pid 99999999] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os/set 'pid [99999999 9]] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os/set 'pid 1] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os/set 'uid [1]] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os/set 'euid "x"] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [access-os/set 'nope 1] reduce [e/id e/arg1 e/arg2 e/arg3]]
[random/seed 1 random 100]
[random/seed 1 random 1000000]
[random/seed 1 random 1.0]
[random/seed 1 random -1.0]
[random/seed 1 random 2.5]
[random/seed 1 random 100%]
[random/seed 1 random 50%]
[random/seed 1 random -1%]
[random 0%]
[random/seed 1 random [1 2 3 4 5]]
[random/seed 1 random/only [1 2 3 4 5]]
[random/seed 1 random "abcdef"]
[random/seed 1 random/only "abcdef"]
[random/seed 1 random #{010203}]
[random/seed 1 random/only #{010203}]
[random/seed 1 random 1.2.3]
[random/seed 1 random 0.0.0]
[random/seed 1 random 10x20]
[random/seed 1 random -10x-20]
[random/seed 1 random 0x0]
[random/seed 1 random #"z"]
[random/seed 1 random 1:00]
[random/seed 1 random -1:00]
[random/seed 1 random 1-Jan-2000]
[random/seed 1 random 1-Jan-2000/10:00]
[random/seed 1 random true]
[random/seed 1 random -10]
[random/seed 1 random make vector! [integer! 8 [1 2 3 4]]]
[random/seed 1 random 4611686018427387904]
[random 0]
[random 0.0]
[random #"^@"]
[random/only []]
[random/only ""]
[random/only #{}]
[random []]
[random/seed "abc" random 100]
[random/seed #{0102} random 100]
[random/seed 1.5 random 100]
[random/seed #"a" random 100]
[random/seed 1.2.3 random 100]
[random/seed 1:00 random 100]
[random/seed 1-Jan-2000 random 100]
[random/seed 1x2 random 100]
[random/seed false random 100]
[x: random/secure 10 all [x >= 1 x <= 10]]
[random/seed 1 random/secure 100]
[random/seed 1 random/secure 1.0]
[random/seed 1 random/secure 100%]
[random/seed 1 random/secure [1 2 3 4 5]]
[random/seed 1 random/secure/only [1 2 3 4 5]]
[random/seed 1 random/secure "abcdef"]
[random/seed 1 random/secure/only "abcdef"]
[random/seed 1 random/secure #{010203}]
[random/seed 1 random/secure/only #{010203}]
[random/seed 1 random/secure 1.2.3]
[random/seed 1 random/secure 10x20]
[random/seed 1 random/secure #"z"]
[random/seed 1 random/secure 1:00]
[random/seed 1 random/secure 1-Jan-2000]
[random/seed 1 random/secure 1-Jan-2000/10:00]
[random/seed 1 random/secure true]
[random/seed 1 random/secure -10]
[random/seed 1 random/secure 1]
[random/seed 1 random/secure 0]
[random/seed 1 random/secure 4611686018427387905]
[random/seed 1 random/secure 9223372036854775807]
[random/seed 1 random/secure -9223372036854775808]
[random/seed 1 random/secure make vector! [integer! 8 [1 2 3 4]]]
[e: try [random none] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [random 'a] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [random $10] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [random quote (1 2)] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [random/only quote (1 2 3)] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [random/seed [1]] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [random/seed make vector! [integer! 8 [1]]] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [random/seed none] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [random/seed 'a] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [random/only make vector! [integer! 8 [1 2 3]]] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [random 4611686018427387905] reduce [e/id e/arg1 e/arg2 e/arg3]]
[e: try [random 9223372036854775807] reduce [e/id e/arg1 e/arg2 e/arg3]]
] [set/any 'e try code print either unset? get/any 'e [{#unset}] [mold/flat/all either error? e [reduce [e/id e/arg1 e/arg2 e/arg3]] [e]]]
