#!/usr/bin/env python3
"""Regenerate docs/obligations.md from the specs.

`allium plan` derives the test obligations a spec implies. This turns them
into the checklist the test audit runs against, one row per obligation
with a column for the test that discharges it.

Existing test assignments are preserved: a row whose obligation id is
already in the file keeps whatever is in its test column. New obligations
arrive as `(none)`, which is the point — a spec change should show up as
an undischarged row rather than quietly widening the gap.

    python3 scripts/obligations.py
"""

import collections
import glob
import json
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(REPO, "docs", "obligations.md")
ROW = re.compile(r"^\| `([^`]+)` — (.*?) \| (.*) \|$")


def existing_assignments():
    """Map obligation id to whatever is currently in its test column."""
    if not os.path.exists(OUTPUT):
        return {}
    assignments = {}
    with open(OUTPUT, encoding="utf-8") as handle:
        for line in handle:
            match = ROW.match(line.rstrip("\n"))
            if match:
                assignments[match.group(1)] = match.group(3)
    return assignments


def plan(spec_path):
    result = subprocess.run(
        ["allium", "plan", spec_path], capture_output=True, text=True
    )
    if result.returncode != 0 and not result.stdout:
        raise SystemExit(f"allium plan failed for {spec_path}: {result.stderr}")
    return json.loads(result.stdout)["obligations"]


def render(by_spec, assignments):
    total = sum(len(obligations) for obligations in by_spec.values())
    discharged = sum(
        1
        for obligations in by_spec.values()
        for obligation in obligations
        if assignments.get(obligation["id"], "(none)") != "(none)"
    )

    lines = [
        "# Test obligations",
        "",
        "Derived from the specs with `allium plan`, one row per obligation,",
        "regenerated by `scripts/obligations.py`. This is the checklist the test",
        "audit runs against: every row gets the test that discharges it beside it,",
        "or the literal `(none)`. A `(none)` that cannot be justified in a line is",
        "an unfinished suite.",
        "",
        "Hunt the gap. The question is \"what has no test\", never \"is this covered\".",
        "",
        f"**{total} obligations** across {len(by_spec)} specs, "
        f"**{discharged} discharged**.",
        "",
    ]

    for spec_name in sorted(by_spec):
        obligations = by_spec[spec_name]
        lines += [f"## {spec_name} ({len(obligations)})", ""]
        groups = collections.defaultdict(list)
        for obligation in obligations:
            groups[obligation["category"]].append(obligation)
        for category in sorted(groups):
            lines += [
                f"### {category} ({len(groups[category])})",
                "",
                "| obligation | test |",
                "|---|---|",
            ]
            for obligation in sorted(groups[category], key=lambda o: o["id"]):
                description = obligation["description"].replace("|", "\\|")
                test = assignments.get(obligation["id"], "(none)")
                lines.append(f"| `{obligation['id']}` — {description} | {test} |")
            lines.append("")

    return "\n".join(lines) + "\n"


def main():
    assignments = existing_assignments()
    by_spec = {
        os.path.basename(path): plan(path)
        for path in sorted(glob.glob(os.path.join(REPO, "spec", "*.allium")))
    }
    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write(render(by_spec, assignments))

    total = sum(len(obligations) for obligations in by_spec.values())
    kept = sum(1 for value in assignments.values() if value != "(none)")
    print(f"docs/obligations.md: {total} obligations, {kept} assignments preserved")
    return 0


if __name__ == "__main__":
    sys.exit(main())
